<?php

namespace Database\Seeders;

use App\Models\RemarketingStepDefinition;
use Illuminate\Database\Seeder;

/**
 * Idempotent seed for the V2 linear default_recovery_v1 flow (definitions only).
 * Run explicitly: php artisan db:seed --class=RemarketingStepDefinitionSeeder
 */
class RemarketingStepDefinitionSeeder extends Seeder
{
    public function run(): void
    {
        $flowKey = RemarketingStepDefinition::FLOW_DEFAULT_RECOVERY_V1;

        $steps = [
            [
                'flow_key' => $flowKey,
                'step_key' => 'fresh_call_1',
                'sequence' => 1,
                'stage' => RemarketingStepDefinition::STAGE_FRESH,
                'action_type' => RemarketingStepDefinition::ACTION_CALL,
                'delay_minutes' => 0,
                'template_name' => null,
                'requires_manual_completion' => true,
                'auto_advance_on_send' => false,
                'stop_if_reengaged' => true,
                'stop_if_dead' => true,
                'stop_if_opted_out' => true,
                'active' => true,
                'instructions' => 'Initial fresh-stage callback attempt. Manual outcome/completion required.',
                'next_step_key' => 'fresh_whatsapp_1',
            ],
            [
                'flow_key' => $flowKey,
                'step_key' => 'fresh_whatsapp_1',
                'sequence' => 2,
                'stage' => RemarketingStepDefinition::STAGE_FRESH,
                'action_type' => RemarketingStepDefinition::ACTION_WHATSAPP,
                'delay_minutes' => 60,
                'template_name' => 'iva-intro-wa-01',
                'requires_manual_completion' => false,
                'auto_advance_on_send' => true,
                'stop_if_reengaged' => true,
                'stop_if_dead' => true,
                'stop_if_opted_out' => true,
                'active' => true,
                'instructions' => 'First WhatsApp follow-up after initial call attempt.',
                'next_step_key' => 'fresh_email_1',
            ],
            [
                'flow_key' => $flowKey,
                'step_key' => 'fresh_email_1',
                'sequence' => 3,
                'stage' => RemarketingStepDefinition::STAGE_FRESH,
                'action_type' => RemarketingStepDefinition::ACTION_EMAIL,
                'delay_minutes' => 180,
                'template_name' => 'iva-benefits-01',
                'requires_manual_completion' => false,
                'auto_advance_on_send' => true,
                'stop_if_reengaged' => true,
                'stop_if_dead' => true,
                'stop_if_opted_out' => true,
                'active' => true,
                'instructions' => 'Benefits/process explainer email.',
                'next_step_key' => 'cooling_call_1',
            ],
            [
                'flow_key' => $flowKey,
                'step_key' => 'cooling_call_1',
                'sequence' => 4,
                'stage' => RemarketingStepDefinition::STAGE_COOLING,
                'action_type' => RemarketingStepDefinition::ACTION_CALL,
                'delay_minutes' => 1440,
                'template_name' => null,
                'requires_manual_completion' => true,
                'auto_advance_on_send' => false,
                'stop_if_reengaged' => true,
                'stop_if_dead' => true,
                'stop_if_opted_out' => true,
                'active' => true,
                'instructions' => 'Cooling-stage callback attempt after first-day touchpoints.',
                'next_step_key' => 'cooling_sms_1',
            ],
            [
                'flow_key' => $flowKey,
                'step_key' => 'cooling_sms_1',
                'sequence' => 5,
                'stage' => RemarketingStepDefinition::STAGE_COOLING,
                'action_type' => RemarketingStepDefinition::ACTION_SMS,
                'delay_minutes' => 2880,
                'template_name' => 'self-serve-sms-01',
                'requires_manual_completion' => false,
                'auto_advance_on_send' => true,
                'stop_if_reengaged' => true,
                'stop_if_dead' => true,
                'stop_if_opted_out' => true,
                'active' => true,
                'instructions' => 'Self-serve / light reactivation SMS.',
                'next_step_key' => 'cooling_whatsapp_2',
            ],
            [
                'flow_key' => $flowKey,
                'step_key' => 'cooling_whatsapp_2',
                'sequence' => 6,
                'stage' => RemarketingStepDefinition::STAGE_COOLING,
                'action_type' => RemarketingStepDefinition::ACTION_WHATSAPP,
                'delay_minutes' => 4320,
                'template_name' => 'self-serve-portal-wa-01',
                'requires_manual_completion' => false,
                'auto_advance_on_send' => true,
                'stop_if_reengaged' => true,
                'stop_if_dead' => true,
                'stop_if_opted_out' => true,
                'active' => true,
                'instructions' => 'WhatsApp nudge directing lead toward portal/self-serve reactivation.',
                'next_step_key' => 'cold_call_1',
            ],
            [
                'flow_key' => $flowKey,
                'step_key' => 'cold_call_1',
                'sequence' => 7,
                'stage' => RemarketingStepDefinition::STAGE_COLD,
                'action_type' => RemarketingStepDefinition::ACTION_CALL,
                'delay_minutes' => 10080,
                'template_name' => null,
                'requires_manual_completion' => true,
                'auto_advance_on_send' => false,
                'stop_if_reengaged' => true,
                'stop_if_dead' => true,
                'stop_if_opted_out' => true,
                'active' => true,
                'instructions' => 'Cold-stage callback attempt after cooling touches.',
                'next_step_key' => 'cold_email_1',
            ],
            [
                'flow_key' => $flowKey,
                'step_key' => 'cold_email_1',
                'sequence' => 8,
                'stage' => RemarketingStepDefinition::STAGE_COLD,
                'action_type' => RemarketingStepDefinition::ACTION_EMAIL,
                'delay_minutes' => 11520,
                'template_name' => 'portal-email-01',
                'requires_manual_completion' => false,
                'auto_advance_on_send' => true,
                'stop_if_reengaged' => true,
                'stop_if_dead' => true,
                'stop_if_opted_out' => true,
                'active' => true,
                'instructions' => 'Portal-focused email touch for colder leads.',
                'next_step_key' => 'dormant_whatsapp_1',
            ],
            [
                'flow_key' => $flowKey,
                'step_key' => 'dormant_whatsapp_1',
                'sequence' => 9,
                'stage' => RemarketingStepDefinition::STAGE_DORMANT,
                'action_type' => RemarketingStepDefinition::ACTION_WHATSAPP,
                'delay_minutes' => 20160,
                'template_name' => 'dormant-final-wa-01',
                'requires_manual_completion' => false,
                'auto_advance_on_send' => true,
                'stop_if_reengaged' => true,
                'stop_if_dead' => true,
                'stop_if_opted_out' => true,
                'active' => true,
                'instructions' => 'Late-stage dormant WhatsApp touch.',
                'next_step_key' => 'dormant_call_1',
            ],
            [
                'flow_key' => $flowKey,
                'step_key' => 'dormant_call_1',
                'sequence' => 10,
                'stage' => RemarketingStepDefinition::STAGE_DORMANT,
                'action_type' => RemarketingStepDefinition::ACTION_CALL,
                'delay_minutes' => 30240,
                'template_name' => null,
                'requires_manual_completion' => true,
                'auto_advance_on_send' => false,
                'stop_if_reengaged' => true,
                'stop_if_dead' => true,
                'stop_if_opted_out' => true,
                'active' => true,
                'instructions' => 'Final dormant-stage callback attempt before cycle completion/stop logic later.',
                'next_step_key' => null,
            ],
        ];

        foreach ($steps as $payload) {
            RemarketingStepDefinition::updateOrCreate(
                [
                    'flow_key' => $payload['flow_key'],
                    'step_key' => $payload['step_key'],
                ],
                $payload
            );
        }
    }
}
