<?php

namespace App\Services;

use App\Models\AssistantConversation;
use App\Models\AssistantKnowledgeItem;
use App\Models\AssistantMessage;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;
use RuntimeException;

class JinxAssistantService
{
    public function __construct(private readonly PartnerKnowledgeService $partnerKnowledge,private readonly DestinationSuitabilityService $destinationSuitability,private readonly ProactiveRoutingService $proactiveRouting,private readonly AssistantIeCalculationService $ieCalculator) {}
    public function reply(AssistantConversation $conversation,string $message): array
    {
        $apiKey=(string)config('services.jinx_assistant.api_key');$model=(string)config('services.jinx_assistant.model');if($apiKey===''||$model==='')throw new RuntimeException('Jinx Assistant is not configured. Set JINX_ASSISTANT_API_KEY and JINX_ASSISTANT_MODEL.');
        $conversation->loadMissing('lead');$facts=$this->establishedFacts($conversation);$profile=$this->partnerKnowledge->profile($conversation->lead?->source,$facts);$knowledge=$this->knowledgeForProfile($profile);$history=$conversation->messages()->latest('id')->limit(24)->get()->reverse()->values()->map(fn(AssistantMessage $item)=>['role'=>$item->role,'content'=>$item->content])->all();$similarCases=$this->findSimilarCases($conversation,$message);$pendingKnowledge=data_get($conversation->metadata,'pending_knowledge');$deterministicBefore=$this->ieCalculator->snapshot($facts,$profile);$comparisonRequested=$this->destinationSuitability->shouldCompare($message);$destinationComparison=$comparisonRequested?$this->destinationSuitability->context():null;
        $instructions=<<<'PROMPT'
You are Jinx Assistant, an expert IVA case-packaging colleague used by trained case packagers inside the Jinx CRM. The user is the case packager, not the client.

WORKFLOW STATE — STRICT
Fact capture is NOT permission to run an I&E. workflow.ie_active is the sole authoritative flag for whether the I&E has started.
If workflow.ie_active is not true, record supplied facts and do not assess DI, suitability, affordability, target achievement or destination fit. Do not describe DETERMINISTIC_IE as a completed/current I&E. If enough core facts were supplied, simply ask whether the packager wants you to carry out the I&E.
If the packager clearly accepts that offer (for example "yes", "carry it out", "run the I&E"), return workflow.ie_active=true in fact_updates and begin the I&E conversational flow.
Once active, ask ONE genuinely missing manual question per message. Do not batch questions.
Do not mark or discuss the I&E as complete until the income stage and required manual expenditure stage are complete.
workflow.income_complete becomes true only after the packager has answered the secondary-income question(s), including a clear "no/none" response. Before that flag is true, never make a DI/suitability conclusion.

INCOME FLOW — STRICT
For Zebra, Child Benefit is calculator-owned. When resident children are established, do NOT ask whether Child Benefit is received and do NOT ask its amount. The deterministic calculator derives it from eligible resident children under the supplied Zebra rules. Ask about Universal Credit and the approved grouped secondary income items still genuinely unknown. A clear "no/none" to the grouped secondary-income question must be stored as zero/none facts as appropriate and workflow.income_complete=true.

CALCULATED EXPENDITURE — STRICT
Never ask for rule-driven SFS figures or Zebra utility figures merely because CRM fields are blank. Electricity, gas and water are calculated from household size under Zebra rules. SFS Housekeeping, Communication & Leisure and Personal are calculated from household composition. Use actual figures only when the packager voluntarily supplies a case-specific amount or the codex explicitly requires a manual amount.

KNOWLEDGE MODEL
Rule precedence is IP-specific > partner-level > company-level. Zebra uses its own rules. Avondale may submit to Lawson Fox, TIG, Assure or Anchorage Chambers. Never transfer one partner/IP rule to another. PARTNER_CODEX is the static baseline and ACTIVE_SCOPED_KNOWLEDGE contains later confirmed scoped rules. Do not invent missing rules.

CROSS-DESTINATION SUITABILITY
Only perform this when explicitly requested OR when workflow.ie_active=true AND workflow.income_complete=true AND the deterministic I&E is sufficiently complete to support the relevant conclusion. Never use a provisional snapshot from fact capture as a routing failure.

TRAINING / NEW RULES
Durable rules must be proposed at company, partner or IP scope and confirmed before saving. Do not save case facts as organisational knowledge.

FACT STORAGE
Return every clear case fact in fact_updates using stable dot-notated keys. Maintain ESTABLISHED_FACTS and never re-ask established facts unless conflicting/insufficient. For a new active Zebra I&E, if calculation.target_di is absent, the first I&E question is exactly "What is the target DI?".
DETERMINISTIC_IE is authoritative arithmetic, but it may exist as a provisional snapshot before the workflow is complete. Do not mistake existence of a snapshot for permission to present a completed I&E or suitability decision.

Return ONLY valid JSON:
{"reply":"natural-language reply","fact_updates":{},"suitability_assessment":null,"proposed_knowledge":null,"confirm_pending_knowledge":false,"case_summary":"brief rolling summary"}
PROMPT;
        $context=['CURRENT_LEAD'=>$this->leadContext($conversation),'PARTNER_PROFILE'=>$profile,'PARTNER_CODEX'=>$profile['partner_codex']??null,'ACTIVE_SCOPED_KNOWLEDGE'=>$knowledge->values()->toArray(),'DESTINATION_COMPARISON'=>$destinationComparison,'ESTABLISHED_FACTS'=>$facts,'DETERMINISTIC_IE'=>$deterministicBefore,'PENDING_KNOWLEDGE_PROPOSAL'=>$pendingKnowledge,'POTENTIALLY_SIMILAR_PRIOR_CASES'=>$similarCases,'CONVERSATION_HISTORY'=>$history,'LATEST_PACKAGER_MESSAGE'=>$message];$response=Http::timeout(60)->withToken($apiKey)->acceptJson()->post('https://api.openai.com/v1/responses',['model'=>$model,'instructions'=>$instructions,'input'=>json_encode($context,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'max_output_tokens'=>$comparisonRequested?2600:1800]);if(!$response->successful())throw new RuntimeException('Assistant provider error: '.$response->status().' '.$response->body());$decoded=json_decode($this->stripCodeFence($this->extractOutputText($response->json())),true);if(!is_array($decoded)||!isset($decoded['reply']))throw new RuntimeException('Assistant returned an invalid response format.');
        $factUpdates=$this->normaliseFactUpdates($decoded['fact_updates']??[]);$factsAfter=array_replace($facts,$factUpdates);$profileAfter=$this->partnerKnowledge->profile($conversation->lead?->source,$factsAfter);$deterministicAfter=$this->ieCalculator->snapshot($factsAfter,$profileAfter);$factsForRouting=$factsAfter;if(($factsAfter['workflow.ie_active']??false)===true&&($factsAfter['workflow.income_complete']??false)===true){$factsForRouting['calculation.disposable_income']=$deterministicAfter['calculation']['disposable_income']??null;$factsForRouting['income.total']=$deterministicAfter['calculation']['income_total']??null;}$reply=trim((string)$decoded['reply']);$suitability=$this->normaliseSuitabilityAssessment($decoded['suitability_assessment']??null);$proactiveSignature=null;if(!$comparisonRequested){$routeAlert=$this->proactiveRouting->evaluate($profileAfter,$factsForRouting,$conversation->lead);if($routeAlert){$signature=sha1(json_encode($routeAlert,JSON_UNESCAPED_SLASHES));if($signature!==(string)data_get($conversation->metadata,'last_proactive_route_signature','')){$proactive=$this->runProactiveComparison($apiKey,$model,$factsForRouting,$routeAlert);if($proactive){$reply.="\n\n".$proactive['reply'];$suitability=$proactive['suitability_assessment'];$proactiveSignature=$signature;}}}}return ['reply'=>$reply,'fact_updates'=>$factUpdates,'deterministic_ie'=>$deterministicAfter,'suitability_assessment'=>$suitability,'proactive_route_signature'=>$proactiveSignature,'proposed_knowledge'=>is_array($decoded['proposed_knowledge']??null)?$this->normaliseKnowledgeProposal($decoded['proposed_knowledge']):null,'confirm_pending_knowledge'=>(bool)($decoded['confirm_pending_knowledge']??false),'case_summary'=>trim((string)($decoded['case_summary']??''))];
    }
    private function runProactiveComparison(string $apiKey,string $model,array $facts,array $routeAlert): ?array {$response=Http::timeout(60)->withToken($apiKey)->acceptJson()->post('https://api.openai.com/v1/responses',['model'=>$model,'instructions'=>'Perform a proactive IVA destination check after an active I&E has reached the required stage. Assess each destination independently. Return only JSON with reply and suitability_assessment.','input'=>json_encode(['ROUTE_ALERT'=>$routeAlert,'ESTABLISHED_FACTS'=>$facts,'DESTINATION_COMPARISON'=>$this->destinationSuitability->context()],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'max_output_tokens'=>2400]);if(!$response->successful())return null;$decoded=json_decode($this->stripCodeFence($this->extractOutputText($response->json())),true);if(!is_array($decoded)||!filled($decoded['reply']??null))return null;return ['reply'=>trim((string)$decoded['reply']),'suitability_assessment'=>$this->normaliseSuitabilityAssessment($decoded['suitability_assessment']??null)];}
    private function knowledgeForProfile(array $profile): Collection {$partner=Str::lower((string)($profile['partner']??''));$ip=Str::lower((string)($profile['ip']??''));return AssistantKnowledgeItem::query()->active()->orderByDesc('updated_at')->limit(250)->get(['id','scope','scope_key','category','title','content','updated_at'])->filter(function(AssistantKnowledgeItem $item)use($partner,$ip){$scope=Str::lower((string)$item->scope);$key=Str::lower(trim((string)$item->scope_key));if($scope==='company')return true;if($scope==='partner')return$partner!==''&&$key===$partner;if($scope==='ip')return$ip!==''&&$key===$ip;return false;});}
    private function establishedFacts(AssistantConversation $conversation): array {$facts=data_get($conversation->metadata,'established_facts',[]);$facts=is_array($facts)?$facts:[];$lead=$conversation->lead;if($lead){if($lead->monthly_housing_cost!==null&&!array_key_exists('housing.rent_mortgage',$facts))$facts['housing.rent_mortgage']=(float)$lead->monthly_housing_cost;if($lead->monthly_council_tax!==null&&!array_key_exists('housing.council_tax',$facts))$facts['housing.council_tax']=(float)$lead->monthly_council_tax;if($lead->estimated_total_debt!==null&&!array_key_exists('case.estimated_total_debt',$facts))$facts['case.estimated_total_debt']=(float)$lead->estimated_total_debt;if($lead->employment_status&&!array_key_exists('client.employment_status',$facts))$facts['client.employment_status']=$lead->employment_status;}return$facts;}
    private function leadContext(AssistantConversation $conversation): ?array {$lead=$conversation->lead;if(!$lead)return null;return ['id'=>$lead->id,'name'=>$lead->formattedName(),'wip_status'=>$lead->wip_status,'source'=>$lead->source,'employment_status'=>$lead->employment_status,'monthly_income'=>$lead->monthly_income,'monthly_housing_cost'=>$lead->monthly_housing_cost,'monthly_council_tax'=>$lead->monthly_council_tax,'monthly_utilities_cost'=>$lead->monthly_utilities_cost,'monthly_food_travel_cost'=>$lead->monthly_food_travel_cost,'estimated_total_debt'=>$lead->estimated_total_debt,'financial_statement'=>$lead->financial_statement];}
    private function findSimilarCases(AssistantConversation $conversation,string $message): array {$keywords=collect(preg_split('/[^a-zA-Z0-9]+/',Str::lower($message))?:[])->filter(fn($word)=>strlen($word)>=5)->reject(fn($word)=>in_array($word,['client','about','would','could','there','their','which','where','should'],true))->unique()->take(6)->values();if($keywords->isEmpty())return[];$query=AssistantMessage::query()->where('role','user')->where('conversation_id','!=',$conversation->id)->whereHas('conversation',fn($q)=>$q->whereNotNull('lead_id'));$query->where(function($q)use($keywords){foreach($keywords as$keyword)$q->orWhere('content','like','%'.$keyword.'%');});return$query->with('conversation:id,lead_id,summary')->latest('id')->limit(5)->get()->unique('conversation_id')->take(3)->map(fn(AssistantMessage $item)=>['lead_id'=>$item->conversation?->lead_id,'conversation_id'=>$item->conversation_id,'summary'=>$item->conversation?->summary,'matching_message_excerpt'=>Str::limit($item->content,350)])->values()->all();}
    private function normaliseFactUpdates(mixed $updates): array {if(!is_array($updates))return[];$normalised=[];foreach(array_slice($updates,0,100,true)as$key=>$value){if(!is_string($key)||strlen($key)>120)continue;if(is_scalar($value)||$value===null)$normalised[$key]=$value;elseif(is_array($value)&&count($value)<=30)$normalised[$key]=array_values($value);}return$normalised;}
    private function normaliseSuitabilityAssessment(mixed $assessment): ?array {if(!is_array($assessment))return null;$allowed=['FIT','NOT_FIT','POSSIBLE_NEEDS_INFO','INSUFFICIENT_RULES'];$destinations=[];foreach(array_slice($assessment['destinations']??[],0,10)as$item){if(!is_array($item))continue;$status=strtoupper((string)($item['status']??''));if(!in_array($status,$allowed,true))$status='POSSIBLE_NEEDS_INFO';$destinations[]=['destination'=>Str::limit((string)($item['destination']??''),120,''),'status'=>$status,'reasons'=>collect($item['reasons']??[])->filter(fn($value)=>is_string($value))->take(10)->values()->all(),'missing'=>collect($item['missing']??[])->filter(fn($value)=>is_string($value))->take(10)->values()->all()];}return ['best_fit'=>filled($assessment['best_fit']??null)?Str::limit((string)$assessment['best_fit'],120,''):null,'best_fit_reason'=>Str::limit((string)($assessment['best_fit_reason']??''),1000,''),'destinations'=>$destinations];}
    private function normaliseKnowledgeProposal(array $proposal): array {$scope=in_array(($proposal['scope']??null),['company','partner','ip'],true)?$proposal['scope']:'company';return ['scope'=>$scope,'scope_key'=>filled($proposal['scope_key']??null)?Str::limit(trim((string)$proposal['scope_key']),120,''):null,'category'=>Str::limit((string)($proposal['category']??'General'),120,''),'title'=>Str::limit((string)($proposal['title']??'Updated rule'),255,''),'content'=>trim((string)($proposal['content']??''))];}
    private function extractOutputText(array $payload): string {if(is_string($payload['output_text']??null)&&$payload['output_text']!=='')return$payload['output_text'];foreach(($payload['output']??[])as$item)foreach(($item['content']??[])as$content)if(isset($content['text'])&&is_string($content['text']))return$content['text'];throw new RuntimeException('Assistant provider returned no text output.');}
    private function stripCodeFence(string $value): string {$value=trim($value);$value=preg_replace('/^```(?:json)?\s*/i','',$value)??$value;$value=preg_replace('/\s*```$/','',$value)??$value;return trim($value);}
}
