<aside class="wip-assistant" id="wipAssistant">
    <div class="wip-assistant__head">
        <div><strong>Jinx Agent</strong><div id="wipAssistantSubtitle">CRM · IVA · Dialler · Research</div></div>
        <button type="button" id="wipAssistantReset">New chat</button>
    </div>
    <div class="wip-assistant__history" id="wipAssistantHistory"><div class="wip-assistant__muted">Loading…</div></div>
    <form id="wipAssistantComposer" class="wip-assistant__composer">
        <textarea id="wipAssistantInput" rows="4" placeholder="Ask Jinx anything — cases, IVA rules, dialler, research or admin…"></textarea>
        <div class="wip-assistant__sendrow"><span id="wipAssistantStatus">Connecting…</span><button type="submit" id="wipAssistantSend">Send</button></div>
    </form>
</aside>
<style>
.wip-assistant{height:100%;box-sizing:border-box;background:linear-gradient(180deg,#111b31 0%,#0f172a 100%);border:1px solid #334155;border-radius:12px;overflow:hidden;display:flex;flex-direction:column;box-shadow:0 16px 40px rgba(0,0,0,.18)}
.wip-assistant__head{padding:14px 16px;border-bottom:1px solid #334155;display:flex;justify-content:space-between;gap:10px;align-items:center}.wip-assistant__head strong{font-size:19px}.wip-assistant__head div div{font-size:11px;color:#64748b;margin-top:3px}.wip-assistant__head button{background:#111827;color:#94a3b8;border:1px solid #334155;border-radius:7px;padding:6px 9px;cursor:pointer}
.wip-assistant__history{flex:1;min-height:0;overflow:auto;padding:14px;scrollbar-width:thin;scrollbar-color:#475569 transparent}.wip-assistant__msg{padding:10px 12px;border-radius:10px;margin-bottom:10px;font-size:13px;line-height:1.5}.wip-assistant__body{white-space:normal}.wip-assistant__body p{margin:0 0 8px}.wip-assistant__body p:last-child{margin-bottom:0}.wip-assistant__body ul,.wip-assistant__body ol{margin:5px 0 9px;padding-left:21px}.wip-assistant__body li{margin:3px 0}.wip-assistant__body h1,.wip-assistant__body h2,.wip-assistant__body h3{font-size:14px;margin:10px 0 5px;color:#f8fafc}.wip-assistant__body code{background:#020617;border:1px solid #334155;border-radius:4px;padding:1px 4px;font-size:12px}.wip-assistant__body a{color:#93c5fd;text-decoration:underline}.wip-assistant__body strong{color:#fff}.wip-assistant__msg--user{margin-left:25px;background:#1d4ed8}.wip-assistant__msg--assistant{margin-right:15px;background:#111827;border:1px solid #334155}.wip-assistant__label{display:block;font-size:9px;font-weight:800;text-transform:uppercase;opacity:.6;margin-bottom:3px}
.wip-assistant__composer{padding:12px;border-top:1px solid #334155}.wip-assistant__composer textarea{box-sizing:border-box;width:100%;resize:vertical;background:#0b1220;color:#f8fafc;border:1px solid #334155;border-radius:9px;padding:10px;font:inherit;font-size:13px}.wip-assistant__sendrow{display:flex;align-items:center;justify-content:space-between;margin-top:8px;font-size:11px;color:#64748b}.wip-assistant__sendrow button{background:#2563eb;color:#fff;border:0;border-radius:8px;padding:8px 14px;font-weight:700;cursor:pointer}.wip-assistant__muted{color:#64748b;font-size:12px}.wip-assistant__tools{display:flex;flex-wrap:wrap;gap:5px;margin-top:9px;padding-top:8px;border-top:1px solid rgba(71,85,105,.45)}.wip-assistant__tools span{font-size:9px;color:#94a3b8;background:#0b1220;border:1px solid #334155;border-radius:999px;padding:3px 6px}
</style>
<script>
(()=>{const history=document.getElementById('wipAssistantHistory'),form=document.getElementById('wipAssistantComposer'),input=document.getElementById('wipAssistantInput'),send=document.getElementById('wipAssistantSend'),status=document.getElementById('wipAssistantStatus'),reset=document.getElementById('wipAssistantReset'),csrf=document.querySelector('meta[name="csrf-token"]')?.content||'';
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const toolLabel=n=>({search_cases:'CRM search',get_case:'Case review',search_internal_knowledge:'Internal rules',get_vicidial_state:'VICIdial',schedule_callback:'Callback booked',update_wip_status:'CRM updated',add_case_note:'Note added',search_jinx_code:'Code search',read_jinx_file:'Code inspected',search_laravel_log:'Logs checked'}[n]||n);
const md=v=>{let x=esc(v).replace(/\r\n/g,'\n');x=x.replace(/```([\s\S]*?)```/g,'<pre><code>$1</code></pre>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');x=x.replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>');x=x.replace(/^[-*] (.+)$/gm,'<li>$1</li>').replace(/((?:<li>.*<\/li>\n?)+)/g,'<ul>$1</ul>');x=x.replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');return x.split(/\n{2,}/).map(b=>/^<(?:h\d|ul|ol|pre)/.test(b)?b:`<p>${b.replace(/\n/g,'<br>')}</p>`).join('');};
const html=m=>{let tools=[...new Set(m.metadata?.agent_activity||[])];let trace=tools.length?`<div class="wip-assistant__tools">${tools.map(x=>`<span>✓ ${esc(toolLabel(x))}</span>`).join('')}</div>`:'';let body=m.role==='user'?esc(m.content).replace(/\n/g,'<br>'):md(m.content);return `<div class="wip-assistant__msg wip-assistant__msg--${m.role==='user'?'user':'assistant'}"><span class="wip-assistant__label">${m.role==='user'?'You':'Jinx'}</span><div class="wip-assistant__body">${body}</div>${trace}</div>`};
const append=m=>{if(history.querySelector('[data-empty]'))history.innerHTML='';history.insertAdjacentHTML('beforeend',html(m));history.scrollTop=history.scrollHeight};
const busy=(on,text)=>{input.disabled=on;send.disabled=on;send.style.opacity=on?'.55':'1';if(text)status.textContent=text};
async function boot(){try{let r=await fetch('/assistant/wip',{headers:{Accept:'application/json'}}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Unable to load');history.innerHTML=d.messages?.length?d.messages.map(html).join(''):'<div class="wip-assistant__muted" data-empty="1">No WIP conversation yet. Ask me what needs doing or book a callback.</div>';history.scrollTop=history.scrollHeight;status.textContent='Ready';document.getElementById('wipAssistantSubtitle').textContent=`CRM · IVA · Dialler · Web · ${d.knowledge_count||0} learned rules`;}catch(e){status.textContent='Unavailable';}}
form.addEventListener('submit',async e=>{e.preventDefault();let message=input.value.trim();if(!message||send.disabled)return;append({role:'user',content:message});input.value='';busy(true,'Jinx is thinking…');try{let r=await fetch('/assistant/wip/message',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify({message})}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Assistant error');append(d.message);status.textContent='Ready';if(/callback booked/i.test(d.message.content))setTimeout(()=>location.reload(),500);}catch(e){append({role:'assistant',content:`I couldn't respond: ${e.message}`});status.textContent='Error';}finally{busy(false);input.focus();}});
input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit();}});
reset.addEventListener('click',async()=>{if(!confirm('Start a new WIP assistant conversation? Shared knowledge will remain.'))return;busy(true,'Starting new chat…');try{await fetch('/assistant/wip/reset',{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf}});history.innerHTML='<div class="wip-assistant__muted" data-empty="1">New WIP conversation started.</div>';status.textContent='Ready';}finally{busy(false);}});boot();})();
</script>
