<button type="button" id="wipAssistantLauncher" class="wip-assistant-launcher" aria-label="Open Jinx Agent" aria-controls="wipAssistant" aria-expanded="false"><span class="wip-assistant-launcher__icon" aria-hidden="true">✦</span><span>Jinx</span></button>
<aside class="wip-assistant" id="wipAssistant" aria-label="Jinx Agent" aria-hidden="true">
    <div class="wip-assistant__head">
        <div><strong>Jinx Agent</strong><div id="wipAssistantSubtitle">CRM · IVA · SIP availability · Dialler · Research</div></div>
        <div class="wip-assistant__head-actions"><button type="button" id="wipAssistantReset">New chat</button><button type="button" id="wipAssistantClose" class="wip-assistant__close" aria-label="Close Jinx Agent">×</button></div>
    </div>
    <div class="wip-assistant__history" id="wipAssistantHistory"><div class="wip-assistant__muted">Loading…</div></div>
    <form id="wipAssistantComposer" class="wip-assistant__composer">
        <textarea id="wipAssistantInput" rows="4" placeholder="Ask Jinx anything — cases, IVA rules, SIP availability, dialler, research or admin…"></textarea>
        <div class="wip-assistant__sendrow"><span id="wipAssistantStatus">Connecting…</span><button type="submit" id="wipAssistantSend">Send</button></div>
    </form>
</aside>
<style>
.wip-assistant-launcher{position:fixed;right:22px;bottom:22px;z-index:11950;display:inline-flex;align-items:center;gap:8px;min-height:48px;border:1px solid #2563eb;border-radius:999px;background:linear-gradient(180deg,#2563eb,#1d4ed8);color:#fff;padding:0 15px 0 12px;font:inherit;font-size:13px;font-weight:900;cursor:pointer;box-shadow:0 16px 36px rgba(2,6,23,.48)}.wip-assistant-launcher:hover{border-color:#60a5fa;transform:translateY(-1px)}.wip-assistant-launcher__icon{display:inline-flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.14);font-size:14px}
.wip-assistant{position:fixed;top:0;right:0;bottom:0;z-index:12000;width:min(460px,calc(100vw - 28px));height:100vh;box-sizing:border-box;background:linear-gradient(180deg,#111b31 0%,#0f172a 100%);border:0;border-left:1px solid #334155;border-radius:0;overflow:hidden;display:flex;flex-direction:column;box-shadow:-18px 0 46px rgba(2,6,23,.56);transform:translateX(105%);transition:transform .18s ease;pointer-events:none}.wip-assistant.is-open{transform:translateX(0);pointer-events:auto}
.wip-assistant__head{padding:14px 16px;border-bottom:1px solid #334155;display:flex;justify-content:space-between;gap:10px;align-items:center;flex-shrink:0}.wip-assistant__head strong{font-size:19px}.wip-assistant__head>div:first-child>div{font-size:11px;color:#64748b;margin-top:3px}.wip-assistant__head-actions{display:flex;align-items:center;gap:6px}.wip-assistant__head button{background:#111827;color:#94a3b8;border:1px solid #334155;border-radius:7px;padding:6px 9px;cursor:pointer}.wip-assistant__head .wip-assistant__close{width:34px;height:34px;padding:0;color:#cbd5e1;font-size:21px;line-height:1}
.wip-assistant__history{flex:1;min-height:0;overflow:auto;padding:14px;scrollbar-width:thin;scrollbar-color:#475569 transparent}.wip-assistant__msg{padding:10px 12px;border-radius:10px;margin-bottom:10px;font-size:13px;line-height:1.5}.wip-assistant__body{white-space:normal}.wip-assistant__body p{margin:0 0 8px}.wip-assistant__body p:last-child{margin-bottom:0}.wip-assistant__body ul,.wip-assistant__body ol{margin:5px 0 9px;padding-left:21px}.wip-assistant__body li{margin:3px 0}.wip-assistant__body h1,.wip-assistant__body h2,.wip-assistant__body h3{font-size:14px;margin:10px 0 5px;color:#f8fafc}.wip-assistant__body code{background:#020617;border:1px solid #334155;border-radius:4px;padding:1px 4px;font-size:12px}.wip-assistant__body a{color:#93c5fd;text-decoration:underline}.wip-assistant__body strong{color:#fff}.wip-assistant__msg--user{margin-left:25px;background:#1d4ed8}.wip-assistant__msg--assistant{margin-right:15px;background:#111827;border:1px solid #334155}.wip-assistant__label{display:block;font-size:9px;font-weight:800;text-transform:uppercase;opacity:.6;margin-bottom:3px}
.wip-assistant__composer{padding:12px;border-top:1px solid #334155;flex-shrink:0}.wip-assistant__composer textarea{box-sizing:border-box;width:100%;resize:vertical;background:#0b1220;color:#f8fafc;border:1px solid #334155;border-radius:9px;padding:10px;font:inherit;font-size:13px}.wip-assistant__sendrow{display:flex;align-items:center;justify-content:space-between;margin-top:8px;font-size:11px;color:#64748b}.wip-assistant__sendrow button{background:#2563eb;color:#fff;border:0;border-radius:8px;padding:8px 14px;font-weight:700;cursor:pointer}.wip-assistant__muted{color:#64748b;font-size:12px}.wip-assistant__tools{display:flex;flex-wrap:wrap;gap:5px;margin-top:9px;padding-top:8px;border-top:1px solid rgba(71,85,105,.45)}.wip-assistant__tools span{font-size:9px;color:#94a3b8;background:#0b1220;border:1px solid #334155;border-radius:999px;padding:3px 6px}
@media(max-width:720px){.wip-assistant-launcher{right:14px;bottom:14px}.wip-assistant{width:100vw}}
</style>
<script>
(()=>{const shell=document.getElementById('wipAssistant'),launcher=document.getElementById('wipAssistantLauncher'),close=document.getElementById('wipAssistantClose'),history=document.getElementById('wipAssistantHistory'),form=document.getElementById('wipAssistantComposer'),input=document.getElementById('wipAssistantInput'),send=document.getElementById('wipAssistantSend'),status=document.getElementById('wipAssistantStatus'),reset=document.getElementById('wipAssistantReset'),csrf=document.querySelector('meta[name="csrf-token"]')?.content||'',storageKey='jinxWipAssistantOpen';if(!shell||!launcher)return;let booted=false,booting=false;
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const toolLabel=n=>({import_vicidial_lead_to_jinx:'Added to Jinx',search_cases:'CRM search',get_case:'Case review',search_internal_knowledge:'Internal rules',save_internal_knowledge:'Rules updated',get_vicidial_state:'VICIdial',search_vicidial_leads:'Dialler search',get_vicidial_history:'Call history',inspect_vicidial_campaign:'Campaign checked',audit_vicidial_hopper:'Hopper audited',summarize_vicidial_activity:'Dialler analysed',update_vicidial_lead_status:'Dialler updated',remove_vicidial_from_hopper:'Hopper cleared',update_vicidial_comments:'Dialler notes updated',check_crm_dialler_consistency:'CRM ↔ Dialler checked',repair_crm_dialler_consistency:'CRM ↔ Dialler repaired',schedule_callback:'Callback booked',cancel_callback:'Callback cancelled',update_wip_status:'CRM updated',add_case_note:'Note added',update_case_field:'Case updated',update_ie_fact:'I&E updated',calculate_ie:'I&E calculated',review_iva_case:'IVA review',calculate_target_di:'Target DI calculated',search_creditors:'Creditor search',update_creditor_contact:'Creditor contact saved',add_debt:'Debt added',update_debt:'Debt updated',delete_debt:'Debt deleted',set_checklist_item:'Checklist updated',search_jinx_code:'Code search',read_jinx_file:'Code inspected',search_laravel_log:'Logs checked'}[n]||n);
const md=v=>{let x=esc(v).replace(/\r\n/g,'\n');x=x.replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');x=x.replace(/```([\s\S]*?)```/g,'<pre><code>$1</code></pre>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');x=x.replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>');x=x.replace(/^[-*] (.+)$/gm,'<li>$1</li>').replace(/((?:<li>.*<\/li>\n?)+)/g,'<ul>$1</ul>');return x.split(/\n{2,}/).map(b=>/^<(?:h\d|ul|ol|pre)/.test(b)?b:`<p>${b.replace(/\n/g,'<br>')}</p>`).join('');};
const html=m=>{let tools=[...new Set(m.metadata?.agent_activity||[])];let trace=tools.length?`<div class="wip-assistant__tools">${tools.map(x=>`<span>✓ ${esc(toolLabel(x))}</span>`).join('')}</div>`:'';let body=m.role==='user'?esc(m.content).replace(/\n/g,'<br>'):md(m.content);return `<div class="wip-assistant__msg wip-assistant__msg--${m.role==='user'?'user':'assistant'}"><span class="wip-assistant__label">${m.role==='user'?'You':'Jinx'}</span><div class="wip-assistant__body">${body}</div>${trace}</div>`};
const append=m=>{if(history.querySelector('[data-empty]'))history.innerHTML='';history.insertAdjacentHTML('beforeend',html(m));history.scrollTop=history.scrollHeight};
const busy=(on,text)=>{input.disabled=on;send.disabled=on;send.style.opacity=on?'.55':'1';if(text)status.textContent=text};
async function boot(){if(booted||booting)return;booting=true;status.textContent='Connecting…';history.innerHTML='<div class="wip-assistant__muted">Loading…</div>';try{let r=await fetch('/assistant/wip',{headers:{Accept:'application/json'}}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Unable to load');history.innerHTML=d.messages?.length?d.messages.map(html).join(''):'<div class="wip-assistant__muted" data-empty="1">No WIP conversation yet. Ask me what needs doing, check SIP availability or book a callback.</div>';history.scrollTop=history.scrollHeight;status.textContent='Ready';document.getElementById('wipAssistantSubtitle').textContent=`CRM · IVA · SIP availability · Dialler · Web · ${d.knowledge_count||0} learned rules`;booted=true;}catch(e){history.innerHTML='<div class="wip-assistant__muted">'+esc(e.message)+'</div>';status.textContent='Unavailable';}finally{booting=false;}}
function setOpen(open){shell.classList.toggle('is-open',open);shell.setAttribute('aria-hidden',open?'false':'true');launcher.setAttribute('aria-expanded',open?'true':'false');sessionStorage.setItem(storageKey,open?'1':'0');if(open){boot();setTimeout(()=>input.focus(),180);}}
launcher.addEventListener('click',()=>setOpen(!shell.classList.contains('is-open')));close.addEventListener('click',()=>setOpen(false));
form.addEventListener('submit',async e=>{e.preventDefault();let message=input.value.trim();if(!message||send.disabled)return;append({role:'user',content:message});input.value='';busy(true,'Jinx is thinking…');try{let r=await fetch('/assistant/wip/message',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify({message})}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Assistant error');append(d.message);status.textContent='Ready';if(/callback booked/i.test(d.message.content))setTimeout(()=>location.reload(),500);}catch(e){append({role:'assistant',content:`I couldn't respond: ${e.message}`});status.textContent='Error';}finally{busy(false);input.focus();}});
input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit();}});
reset.addEventListener('click',async()=>{if(!confirm('Start a new WIP assistant conversation? Shared knowledge will remain.'))return;busy(true,'Starting new chat…');try{await fetch('/assistant/wip/reset',{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf}});history.innerHTML='<div class="wip-assistant__muted" data-empty="1">New WIP conversation started. Ask about a case, SIP availability or anything else.</div>';status.textContent='Ready';}finally{busy(false);}});
document.addEventListener('keydown',e=>{if(e.altKey&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&String(e.key||'').toLowerCase()==='j'){e.preventDefault();setOpen(!shell.classList.contains('is-open'));}});
if(sessionStorage.getItem(storageKey)==='1')setTimeout(()=>setOpen(true),0);
})();
</script>
